### ISSUE TITLE
OSV-2021-1549 fix commit is incorrect

### ISSUE THREAD

**Issue by Marcono1234** [google/oss-fuzz-vulns#22]
The fix commit for OSV-2021-1549 seems to be incorrect. It claims the issue was fixed in https://github.com/google/gson/commit/b0595c595bd2c052cd05e0283bb37b67c02bd06f.

Unfortunately I don't have access to the detailed OSS-Fuzz report, but when I run it locally I get a `StackOverflowError` which also seems to match what you might expect from the reproducer test case (large number of nested `[`).

I am not completely sure why OSS-Fuzz thought commit `b0595c5` fixes this issue, because I am still seeing a `StackOverflowError` with that commit (unless my local OSS-Fuzz setup is incorrect). Maybe the changed line numbers in the stack trace (700 to 701) confused it. The real fix for this is most likely https://github.com/google/gson/commit/2d01d6a20f39881c692977564c1ea591d9f39027, which also fixed similar OSS-Fuzz issues:
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40790
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=43303

**Comment by oliverchang** [comment]
Thanks for reporting this! 

Our infrastructure does its best to bisect/identify the correct fix commit, but occasionally does stumble in cases like these. 

I've manually fixed up this instance in https://github.com/google/oss-fuzz-vulns/commit/74fec8ef782f3ce6d57369b931a798aa120d1d88.
