### ISSUE TITLE
False Positive on arrow vs. pyarrow

### ISSUE THREAD

**Issue by KyleKing** [google/oss-fuzz-vulns#23]
I'm not sure where the right place is to raise this issue, but there is a fixed vulnerability incorrectly attributed to all version of the wrong package, [`arrow-py/arrow`](https://github.com/arrow-py/arrow) ([arrow](https://pypi.org/project/arrow/)). The correct package is [`apache/arrow`](https://github.com/apache/arrow) ([pyarrow](https://pypi.org/project/pyarrow/))

See the report of the false positive here: https://deps.dev/advisory/osv/OSV-2021-1565 which links from:

https://github.com/google/oss-fuzz-vulns/blob/cfc07c5bff1ea53cc6466591eb25b17f1e3780f0/vulns/arrow/OSV-2021-1565.yaml#L13-L21

In `pyarrow`, this vulnerability has already been fixed in: https://github.com/apache/arrow/compare/3abab2ee044b405476844fbffebfaab8e3350207...641554b0bcce587549bfcfd0cde3cb4bc23054aa (linked from: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40902#c6)

**Comment by oliverchang** [comment]
Hi! 

Thanks for filing this issue. The package that's listed here is "OSS-Fuzz/arrow", which refers to the "arrow" project as integrated into OSS-Fuzz, and not necessary any package on the PyPI registry. There is a known FR to get this attached to the correct ecosystem (i.e. PyPI) package name: https://github.com/google/oss-fuzz/issues/6956.

For the range itself, our automation failed to automatically identify the correct affected commit ranges here. I've fixed this in https://github.com/google/oss-fuzz-vulns/blob/main/vulns/arrow/OSV-2021-1565.yaml

**Comment by KyleKing** [comment]
Great, thanks!
