### ISSUE TITLE
Removing entries

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz-vulns#27]
According to https://github.com/google/oss-fuzz-vulns#removing-an-entry
> If a vulnerability in this repository is not considered a security vulnerability, it may be removed by submitting a PR to delete the corresponding files.

I think it should be possible to remove entries like that once and for all if necessary but given that links to OSV entries pop up in various places as soon as they end up in the OSV database I think it would be better to add the "withdrawn" field instead. My guess would be that it had been written before [the "withdrawn" field](https://ossf.github.io/osv-schema/#withdrawn-field) was added to the specification.

**Comment by oliverchang** [comment]
Thanks, yep! `withdrawn` is indeed the preferred mechanism for this. I'll update the docs.
