### ISSUE TITLE
OSV-2017-16.yaml is missing introduced & fixed attributes

### ISSUE THREAD

**Issue by ddkilzer** [google/oss-fuzz-vulns#28]
[OSV-2017-16.yaml](https://github.com/google/oss-fuzz-vulns/blob/main/vulns/file/OSV-2017-16.yaml) is missing introduced & fixed attributes.

The original oss-fuzz [Issue 750](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=750) includes this information:

> Regressed: https://oss-fuzz.com/revisions?job=libfuzzer_asan_file&range=201611301805:201612010819
> Fixed: https://oss-fuzz.com/revisions?job=libfuzzer_asan_file&range=201703160224:201703161623

Originally reported on Twitter:  <https://twitter.com/ddkilzer/status/1609630551534866432>

**Comment by oliverchang** [comment]
Thanks for reporting! This is now fixed in https://github.com/google/oss-fuzz-vulns/blob/main/vulns/file/OSV-2017-16.yaml. Let us know if this still looks incorrect.
