### ISSUE TITLE
OSV-2020-2324.yaml has incorrect introduced & fixed attributes

### ISSUE THREAD

**Issue by ddkilzer** [google/oss-fuzz-vulns#29]
[OSV-2020-2324.yaml](https://github.com/google/oss-fuzz-vulns/blob/main/vulns/libarchive/OSV-2020-2324.yaml) has incorrect introduced & fixed attributes.

The original oss-fuzz [Issue 21048](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21048) includes this information:

> Regressed: https://oss-fuzz.com/revisions?job=honggfuzz_asan_libarchive&range=202003020328:202003030327
> ClusterFuzz testcase 5688058864467968 is verified as fixed in https://oss-fuzz.com/revisions?job=honggfuzz_asan_libarchive&range=202003050329:202003060336

However, both of those links go to the same commit:  [f001f3b0e6a66a7eb989ed3783791c0316831202](https://github.com/libarchive/libarchive/commit/f001f3b0e6a66a7eb989ed3783791c0316831202)

Based on the commit message (and the dates of the oss-fuzz issue), the likely regression is this commit:  [d84ec3fbc21ff943b4c742ec141de30efc8bd769](https://github.com/libarchive/libarchive/commit/d84ec3fbc21ff943b4c742ec141de30efc8bd769)

This means this issue was a very short-lived regression, and it did not ever ship.

**Comment by ddkilzer** [comment]
Looking at the two commits that caused the regression, as well as the fixed commit, they're all in the same set of tags:

```
$ git tag --contains 85b9f665b6a2d4397fdd38992152d011265e374b
v3.4.3
v3.5.0
v3.5.1
v3.5.2
v3.5.3
v3.6.0
v3.6.1
v3.6.2
```

```
$ git tag --contains d84ec3fbc21ff943b4c742ec141de30efc8bd769
v3.4.3
v3.5.0
v3.5.1
v3.5.2
v3.5.3
v3.6.0
v3.6.1
v3.6.2
```

```
$ git tag --contains f001f3b0e6a66a7eb989ed3783791c0316831202
v3.4.3
v3.5.0
v3.5.1
v3.5.2
v3.5.3
v3.6.0
v3.6.1
v3.6.2
```

Based on that information, I don't think this bug ever shipped.

**Comment by oliverchang** [comment]
Thanks, the fact that our initial CF bisection pointed to the same commit indicates that this entry is likely to be completely wrong (e.g. a false positive caused by a build configuration on oss-fuzz's side). 

I've marked this entry as withdrawn.
